### PR TITLE
Update CMake/common for documentation plans

### PR DESCRIPTION
**Pull request by rdumusc**

### CODE REVIEW

**Comment by rdumusc** [comment]
Thanks for the +1s. I am bumping the minor version of projects which have changes since the last release, so that the documentation of the released version is not overwritten. I'm assigning those for review.

**Comment by rdumusc** [comment]
Note that this is open for discussion; it is also possible to not bump the versions, but then documentation plans shouldn't be automatic but run manually at release time.

**Comment by eile** [comment]
> but then documentation plans shouldn't be automatic but run manually at release time.

Not sure if I get the context -- once we've activated this to run automatically, the documentation will always be up-to-date by release time. We just have to be double careful to bump minor directly after the release.

**Comment by rdumusc** [comment]
Yes, with automatic plans activated the current version will be constantly up-to-to date, so we would have to bump the version in the commit that follows the release. (Or do development in a branch, then merge back when we are ready.)

**Pull request merged**
