### PR TITLE
Clean up Vector::getSubVector()

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by tribal-tec** [comment]
API breakage?

**Comment by eile** [comment]
Yes, but we have to start somehow... I was pondering as well. Downstream projects are prepared.

**Comment by tribal-tec** [comment]
I'm not sure about starting somehow means this. I could also mean use something we don't have to maintain ourselves, if we are anyway supposed to change all downstream projects. GLM still seems a viable option to me in most of the cases.

**Comment by eile** [comment]
updated

**Pull request merged**
